# Generated by Django 2.2.6 on 2020-01-07 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_Name', models.CharField(default='null', max_length=200)),
            ],
            options={
                'verbose_name': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_teaching', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Professor',
            },
        ),
        migrations.CreateModel(
            name='User2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('user_type', models.CharField(default='null', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_documents', models.IntegerField(default=0)),
                ('number', models.CharField(default=0, max_length=200)),
                ('teacher', models.BooleanField(default=False)),
                ('course', models.ManyToManyField(blank=True, to='plagiarism.Courses')),
            ],
            options={
                'verbose_name': 'Student',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='.', max_length=200)),
                ('sub_date', models.DateTimeField(auto_now_add=True)),
                ('document', models.FileField(null=True, upload_to='documents/')),
                ('keywords', models.CharField(max_length=500, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plagiarism.Courses')),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plagiarism.User2'),
        ),
    ]
