# Generated by Django 2.2.6 on 2020-01-07 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plagiarism', '0003_document_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='evaluator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plagiarism.User2'),
        ),
    ]
